In [1]:
from tabula import read_pdf
import pandas as pd

df = read_pdf("../data/raw/students/prishtine_numri_i_pergjithshem_bachelor.pdf")

In [2]:
# TODO(Add Master's values)
df_up = df.iloc[:,-3:]
df_up.columns = ["Femra", "Meshkuj", "Gjithsej"]
df_up = df_up.iloc[16]
# df_up["Emri"] = "Universiteti i Prishtinës"

df_prishtine_master = pd.read_csv(
    "../data/raw/students/prishtine_master.csv",
    encoding="iso-8859-1",
    sep=";",
    header=1,
    na_values="-",
)

df_all = pd.DataFrame([[sum(x) for x in zip(list(df_up.astype(float).values), [
    df_prishtine_master.iloc[-1,2::2].sum(),
    df_prishtine_master.iloc[-1,3::2].sum(),
    df_prishtine_master.iloc[-1,2::2].sum()+df_prishtine_master.iloc[-1,3::2].sum(),
])]+["Universiteti i Prishtinës"]], columns=["Femra", "Meshkuj", "Gjithsej", "Emri"])

In [3]:
df_ferizaj_bachelor = pd.read_csv(
    "../data/raw/students/ferizaj_bachelor.csv",
    encoding="iso-8859-1",
    sep=";",
    header=1,
    na_values="-",
)
df_ferizaj_master = pd.read_csv(
    "../data/raw/students/ferizaj_bachelor.csv",
    encoding="iso-8859-1",
    sep=";",
    header=1,
    na_values="-",
)

df_all = df_all.append(pd.DataFrame([[
    df_ferizaj_bachelor.iloc[-1,2::3].sum()+df_ferizaj_master.iloc[-1,2::3].sum(),
    df_ferizaj_bachelor.iloc[-1,3::3].sum()+df_ferizaj_master.iloc[-1,3::3].sum(),
    df_ferizaj_bachelor.iloc[-1,4::3].sum()+df_ferizaj_master.iloc[-1,4::3].sum(),
    "Universiteti i Shkencave të Aplikuara Ferizaj"
]],columns=df_all.columns))

In [4]:
df_gjakove_bachelor = pd.read_csv(
    "../data/raw/students/gjakove_bachelor.csv",
    encoding="iso-8859-1",
    sep=";",
    header=1,
    na_values="-",
)

df_all = df_all.append(pd.DataFrame([[
    df_gjakove_bachelor.iloc[-1,2::3].sum(),
    df_gjakove_bachelor.iloc[-1,3::3].sum(),
    df_gjakove_bachelor.iloc[-1,4::3].sum(),
    "Universiteti i Gjakovës Fehmi Agani"
]],columns=df_all.columns))

In [5]:
df_gjilan_bachelor = pd.read_csv(
    "../data/raw/students/gjilan_bachelor.csv",
    encoding="iso-8859-1",
    sep=";",
    header=1,
    na_values="-",
)

df_all = df_all.append(pd.DataFrame([[
    df_gjilan_bachelor.iloc[-1,3::3].sum(),
    df_gjilan_bachelor.iloc[-1,4::3].sum(),
    df_gjilan_bachelor.iloc[-1,2::3].sum(),
    "Universiteti Kadri Zeka Gjilan"
]],columns=df_all.columns))

In [6]:
df_islame_bachelor = pd.read_csv(
    "../data/raw/students/islame_bachelor.csv",
    encoding="iso-8859-1",
    sep=";",
    header=1,
    na_values="-",
)

df_islame_master = pd.read_csv(
    "../data/raw/students/islame_master.csv",
    encoding="iso-8859-1",
    sep=";",
    header=1,
    na_values="-",
)

df_all = df_all.append(pd.DataFrame([[
    df_islame_bachelor.iloc[-1,2::3].sum()+df_islame_master.iloc[-1,2::3].sum(),
    df_islame_bachelor.iloc[-1,3::3].sum()+df_islame_master.iloc[-1,3::3].sum(),
    df_islame_bachelor.iloc[-1,4::3].sum()+df_islame_master.iloc[-1,4::3].sum(),
    "Fakulteti i Studimeve Islame"
]],columns=df_all.columns))

In [7]:
df_kolegjet_bachelor = pd.read_csv(
    "../data/raw/students/kolegjet_bachelor.csv",
    encoding="iso-8859-1",
    sep=";",
    header=1,
    na_values=["-", ":"],
)

df_kolegjet_master = pd.read_csv(
    "../data/raw/students/kolegjet_master.csv",
    encoding="iso-8859-1",
    sep=";",
    header=1,
    na_values=["-", ":"],
)

df_all = df_all.append(pd.DataFrame([[
    df_kolegjet_bachelor.iloc[-1,2::2].sum()+df_kolegjet_master.iloc[-1,2::2].sum(),
    df_kolegjet_bachelor.iloc[-1,3::2].sum()+df_kolegjet_master.iloc[-1,3::2].sum()-df_kolegjet_bachelor.iloc[-1,2::2].sum()-df_kolegjet_master.iloc[-1,2::2].sum(),
    df_kolegjet_bachelor.iloc[-1,3::2].sum()+df_kolegjet_master.iloc[-1,3::2].sum(),
    "Kolegjet"
]],columns=df_all.columns))

df_all = df_all.append(pd.DataFrame([[
    df_kolegjet_bachelor.iloc[0,2::2].sum()+df_kolegjet_master.iloc[0,2::2].sum(),
    df_kolegjet_bachelor.iloc[0,3::2].sum()+df_kolegjet_master.iloc[0,3::2].sum()-df_kolegjet_bachelor.iloc[0,2::2].sum()-df_kolegjet_master.iloc[0,2::2].sum(),
    df_kolegjet_bachelor.iloc[0,3::2].sum()+df_kolegjet_master.iloc[0,3::2].sum(),
    "Kolegji AAB"
]],columns=df_all.columns))

df_all = df_all.append(pd.DataFrame([[
    df_kolegjet_bachelor.iloc[18,2::2].sum()+df_kolegjet_master.iloc[18,2::2].sum(),
    df_kolegjet_bachelor.iloc[18,3::2].sum()+df_kolegjet_master.iloc[18,3::2].sum()-df_kolegjet_bachelor.iloc[18,2::2].sum()-df_kolegjet_master.iloc[18,2::2].sum(),
    df_kolegjet_bachelor.iloc[18,3::2].sum()+df_kolegjet_master.iloc[18,3::2].sum(),
    "Kolegji UBT"
]],columns=df_all.columns))

df_all = df_all.append(pd.DataFrame([[
    df_kolegjet_bachelor.iloc[4,2::2].sum()+df_kolegjet_master.iloc[4,2::2].sum(),
    df_kolegjet_bachelor.iloc[4,3::2].sum()+df_kolegjet_master.iloc[4,3::2].sum()-df_kolegjet_bachelor.iloc[4,2::2].sum()-df_kolegjet_master.iloc[4,2::2].sum(),
    df_kolegjet_bachelor.iloc[4,3::2].sum()+df_kolegjet_master.iloc[4,3::2].sum(),
    "Kolegji FAMA"
]],columns=df_all.columns))

In [8]:
# Mitrovice
df_mitrovice_bachelor = pd.read_csv(
    "../data/raw/students/mitrovice_bachelor.csv",
    encoding="iso-8859-1",
    sep=";",
    header=1,
    na_values="-",
)
df_mitrovice_master = pd.read_csv(
    "../data/raw/students/mitrovice_master.csv",
    encoding="iso-8859-1",
    sep=";",
    header=1,
    na_values="-",
)

df_all = df_all.append(pd.DataFrame([[
    df_mitrovice_bachelor.iloc[-1,2::2].sum()+df_mitrovice_master.iloc[-1,2::2].sum(),
    df_mitrovice_bachelor.iloc[-1,3::2].sum()+df_mitrovice_master.iloc[-1,3::2].sum(),
    df_mitrovice_bachelor.iloc[-1,4::3].sum()+df_mitrovice_master.iloc[-1,4::3].sum()+df_mitrovice_bachelor.iloc[-1,3::2].sum()+df_mitrovice_master.iloc[-1,3::2].sum(),
    "Universiteti Isa Boletini Mitrovicë"
]],columns=df_all.columns))

In [10]:
# Peje
df_peje_bachelor = pd.read_csv(
    "../data/raw/students/peje_bachelor.csv",
    encoding="iso-8859-1",
    sep=";",
    header=1,
    na_values=["-",":"],
)
df_peje_master = pd.read_csv(
    "../data/raw/students/peje_master.csv",
    encoding="iso-8859-1",
    sep=";",
    header=1,
    na_values=["-",":"],
)

df_all = df_all.append(pd.DataFrame([[
    df_peje_bachelor.iloc[-1,3::3].sum()+df_peje_master.iloc[-1,3::3].sum(),
    df_peje_bachelor.iloc[-1,4::3].sum()+df_peje_master.iloc[-1,4::3].sum(),
    df_peje_bachelor.iloc[-1,2::3].sum()+df_peje_master.iloc[-1,2::3].sum(),
    "Universiteti Haxhi Zeka Pejë"
]],columns=df_all.columns))

In [11]:
# Prizren
df_prizren_bachelor_master = pd.read_csv(
    "../data/raw/students/prizren_bachelor_master.csv",
    encoding="iso-8859-1",
    sep=";",
    header=1,
    na_values="-",
)

df_all = df_all.append(pd.DataFrame([[
    df_prizren_bachelor_master.iloc[-1,3::3].sum(),
    df_prizren_bachelor_master.iloc[-1,4::3].sum(),
    df_prizren_bachelor_master.iloc[-1,2::3].sum(),
    "Universiteti i Prizrenit Ukshin Hoti"
]],columns=df_all.columns))

In [12]:
# Vushtrri
df_vushtrri_bachelor = pd.read_csv(
    "../data/raw/students/vushtrri_bachelor.csv",
    encoding="iso-8859-1",
    sep=";",
    header=1,
    na_values="-",
)

df_all = df_all.append(pd.DataFrame([[
    df_vushtrri_bachelor.iloc[-1,2::3].sum(),
    df_vushtrri_bachelor.iloc[-1,3::3].sum(),
    df_vushtrri_bachelor.iloc[-1,4::3].sum(),
    "Fakulteti për Siguri Publike-Vushtrri"
]],columns=df_all.columns))

In [15]:
df = df_all.reset_index(drop=True)

In [28]:
dff = df.drop(5).reset_index(drop=True)

In [29]:
dff

      Femra  Meshkuj  Gjithsej                                           Emri
0   23697.0  17443.0   41140.0                      Universiteti i Prishtinës
1    1280.0   1236.0    2516.0  Universiteti i Shkencave të Aplikuara Ferizaj
2    1685.0    688.0    2373.0            Universiteti i Gjakovës Fehmi Agani
3    4790.0   6204.0   10994.0                 Universiteti Kadri Zeka Gjilan
4     150.0    227.0     377.0                   Fakulteti i Studimeve Islame
5    8259.0   7211.0   15470.0                                    Kolegji AAB
6    3200.0   5249.0    8449.0                                    Kolegji UBT
7    2031.0   1331.0    3362.0                                   Kolegji FAMA
8    3635.0   2506.0    5525.0            Universiteti Isa Boletini Mitrovicë
9    5759.0   6934.0   12693.0                   Universiteti Haxhi Zeka Pejë
10   4056.0   2740.0    6796.0           Universiteti i Prizrenit Ukshin Hoti
11     18.0    161.0     179.0          Fakulteti për Siguri Publike-Vushtrri

In [27]:
dff.to_csv("../data/processed/students.csv",index=False)

In [20]:
test = df.drop([6,7,8]).reset_index(drop=True)

In [21]:
test.loc["Total",:] = df.sum(axis=0)

In [24]:
test.to_csv("../data/processed/students_all.csv",index=False)